source 'https://github.com/CocoaPods/Specs.git'

def shared_pods
    pod 'AFNetworking', '~> 2.6'
    pod 'SSKeychain', :git => 'https://github.com/soffes/sskeychain.git', :branch => 'watchos'
end

target 'ChatApp' do
    platform :ios, '8.0'
    shared_pods
end

target 'ChatApp WatchKit Extension' do
    platform :watchos, '2.0'
    shared_pods
end
